stages:
  - build1
  - build2
jobs:
  include:
    - stage: build1
      script: ./travis-ci1.sh
    - stage: build2
      script: ./travis-ci2.sh
dist: bionic
language: cpp
cache:
   directories:
    - $HOME/.cache/bazel/
